name: gen
description: "A new Flutter package project."
version: 0.0.1
homepage: none

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  json_annotation: ^4.9.0 
  flutter_svg: ^2.2.0
  lottie: ^3.3.1
  envied: ^1.2.0
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  very_good_analysis: ^9.0.0 
  build_runner: ^2.7.0
  envied_generator: ^1.2.0
  json_serializable: ^6.11.0 
  flutter_gen_runner: ^5.11.0

flutter_gen:
  output: lib/src/asset/

  integrations:
    flutter_svg: true
    lottie: true 
  
  colors:
    inputs:
      - assets/color/colors.xml

flutter:
  assets:
    - assets/images/
    - assets/icons/
    - assets/env/
    - assets/lottie/